### ISSUE TITLE
Huge problems with case-insensitive search

### ISSUE THREAD

**Issue by svauban** [auto-complete/fuzzy-el#8]
As you can see on https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21148, there are conflicts between Fuzzy and Emacs 25.0.

Would you mind taking a look at it?  @Malabarba proposed to help you, if needed.

Best regards!

**Comment by Malabarba** [comment]
The problem is with the fuzzy-isearch function. It assumes that a non-nil isearch-word value always means the same thing. In reality that variable's value can also be a function, which is then used on the search string. This has been the case for a while now, that's how symbol-searching was implemented.

**Comment by Malabarba** [comment]
The solution is to just replace the first clause of that cond with a call to isearch-fun-default, so you'll let isearch take care of all that for you.

**Comment by Malabarba** [comment]
@svauban 
To fix your problem, you can define `fuzzy-isearch` like this in your init file. 

    (defun fuzzy-isearch ()
      (cond ((or isearch-word isearch-regexp) 
             (isearch-search-fun-default))
            ((or fuzzy-isearch
                 (eq fuzzy-isearch-enabled 'always)
                 (and (eq fuzzy-isearch-enabled 'on-failed)
                      (null isearch-success)
                      isearch-wrapped
                      (> (incf fuzzy-isearch-failed-count) 1)))
             (unless fuzzy-isearch
               (fuzzy-isearch-activate))
             (if isearch-forward 'fuzzy-search-forward 'fuzzy-search-backward))
            (t
             (if isearch-forward 'search-forward 'search-backward))))

You'll probably also have to set `char-fold-search` to `nil`.

**Comment by syohex** [comment]
@svauban @Malabarba Could you send pull request ?

**Comment by Malabarba** [comment]
Next time I have some free time, sure, but that could take a couple of months. :) (I'm currently in the process of writing my thesis)

But feel free to take that code I posted above and commit it as yours. I don't mind.

**Comment by syohex** [comment]
@svauban I have applied @Malabarba patch at #9. Please check latest version.

**Comment by svauban** [comment]
Perfect!  Thanks to both of you.

**Comment by Malabarba** [comment]
Thanks for your work @syohex !
